# Generated by Django 5.0.8 on 2024-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_as_customer', models.IntegerField()),
                ('age', models.IntegerField()),
                ('policy_number', models.CharField(max_length=50)),
                ('policy_bind_date', models.DateTimeField()),
                ('policy_state', models.CharField(max_length=10)),
                ('policy_csl', models.CharField(max_length=20)),
                ('policy_deductable', models.FloatField()),
                ('policy_annual_premium', models.FloatField()),
                ('umbrella_limit', models.FloatField()),
                ('insured_zip', models.CharField(max_length=10)),
                ('insured_sex', models.CharField(max_length=10)),
                ('insured_education_level', models.CharField(max_length=50)),
                ('insured_occupation', models.CharField(max_length=50)),
                ('insured_hobbies', models.CharField(max_length=50)),
                ('insured_relationship', models.CharField(max_length=20)),
                ('capital_gains', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('incident_date', models.DateTimeField()),
                ('incident_type', models.CharField(max_length=50)),
                ('collision_type', models.CharField(max_length=50)),
                ('incident_severity', models.CharField(max_length=50)),
                ('authorities_contacted', models.CharField(max_length=50)),
                ('incident_state', models.CharField(max_length=10)),
                ('incident_city', models.CharField(max_length=50)),
                ('incident_location', models.CharField(max_length=100)),
                ('incident_hour_of_the_day', models.IntegerField()),
                ('number_of_vehicles_involved', models.IntegerField()),
                ('property_damage', models.CharField(max_length=10)),
                ('bodily_injuries', models.IntegerField()),
                ('witnesses', models.IntegerField()),
                ('police_report_available', models.CharField(max_length=10)),
                ('total_claim_amount', models.FloatField()),
                ('injury_claim', models.FloatField()),
                ('property_claim', models.FloatField()),
                ('vehicle_claim', models.FloatField()),
                ('auto_make', models.CharField(max_length=50)),
                ('auto_model', models.CharField(max_length=50)),
                ('auto_year', models.IntegerField()),
                ('fraud_reported', models.CharField(max_length=1)),
            ],
        ),
    ]
